name: 📦 Release

on:
 push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:
  release:
    name: Build & Publish ${{ matrix.target }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: x86_64-pc-windows-gnu
            archive: zip
          - target: x86_64-unknown-linux-musl
            archive: tar.gz tar.xz tar.zst
          - target: x86_64-apple-darwin
            archive: zip

    steps:
      # 1) Check out your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2) Build & archive using rust-build.action
      - name: Compile & archive (${{ matrix.target }})
        uses: rust-build/rust-build.action@v1.4.5
        env:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

