name: 📦 Release

on:
 push:
    tags:
      - '**[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'

